# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import color_typed as module_0


def test_case_0():
    str_0 = "0URl}x5 oi8A"
    str_1 = module_0.stringc(str_0, str_0)
    assert str_1 == "0URl}x5 oi8A"
    assert module_0.ANSIBLE_COLOR is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "this loader is only for sub-collection modules/packages, not {0}"
    module_0.parsecolor(str_0)


def test_case_2():
    str_0 = "ybR+n&6"
    str_1 = module_0.colorize(str_0, str_0, str_0)
    assert str_1 == "ybR+n&6=ybR+n&6"
    assert module_0.ANSIBLE_COLOR is False


def test_case_3():
    bool_0 = False
    str_0 = module_0.colorize(bool_0, bool_0, bool_0)
    assert str_0 == "False=False"
    assert module_0.ANSIBLE_COLOR is False


def test_case_4():
    str_0 = "Y/{q7-t)!iMpc=OCuN>="
    str_1 = module_0.hostcolor(str_0, str_0)
    assert str_1 == "Y/{q7-t)!iMpc=OCuN>=      "
    assert module_0.ANSIBLE_COLOR is False
