# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import splitter as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xcd\x10\x00\xa5\x15\x9dw\xda\xde\x04"
    module_0.split_args(bytes_0)


def test_case_1():
    str_0 = "$"
    var_0 = module_0.unquote(str_0)
    assert var_0 == "$"


def test_case_2():
    str_0 = ""
    var_0 = module_0.unquote(str_0)
    assert var_0 == ""


def test_case_3():
    str_0 = '"edaYS#6.E]Q\x0b{PC\\t\x0b'
    var_0 = module_0.is_quoted(str_0)
    assert var_0 is False


def test_case_4():
    str_0 = "'Y\x0b|onBjMZTus?<"
    var_0 = module_0.unquote(str_0)
    assert var_0 == "'Y\x0b|onBjMZTus?<"


def test_case_5():
    str_0 = '"'
    var_0 = module_0.unquote(str_0)
    assert var_0 == ""
