# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import splitter_typed as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xeaTj\xfb\xfd<\x1aC1"
    module_0.split_args(bytes_0)


def test_case_1():
    str_0 = "UbnFSxcd{u?M"
    bool_0 = module_0.is_quoted(str_0)
    assert bool_0 is False


def test_case_2():
    bytes_0 = b""
    bool_0 = module_0.is_quoted(bytes_0)
    assert bool_0 is False


def test_case_3():
    str_0 = ">Jr.IDLjE4Z#ji"
    str_1 = module_0.unquote(str_0)
    assert str_1 == ">Jr.IDLjE4Z#ji"


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "'"
    bytes_0 = b"\xd8[-\xbb\xdd\xaa\x1cL\xbep<\x13.\x97\x94\x8d2"
    str_1 = module_0.unquote(str_0)
    assert str_1 == ""
    module_0.split_args(bytes_0)


def test_case_5():
    str_0 = "'a6r'@\x0bZQZQ(hQ"
    str_1 = module_0.unquote(str_0)
    assert str_1 == "'a6r'@\x0bZQZQ(hQ"


def test_case_6():
    str_0 = "\"|{ofo'/HV_h__yM,IE."
    str_1 = module_0.unquote(str_0)
    assert str_1 == "\"|{ofo'/HV_h__yM,IE."


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = "mm"
    str_1 = module_0.unquote(str_0)
    assert str_1 == "mm"
    str_2 = '"'
    bool_0 = module_0.is_quoted(str_2)
    assert bool_0 is True
    none_type_0 = None
    module_0.split_args(none_type_0)
